import os
import sys
import tempfile
from pathlib import Path

import pytest

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))

_TEST_DIR = Path(tempfile.mkdtemp(prefix="shoplab_test_"))
os.environ["DATABASE_URL"] = str(_TEST_DIR / "test.db")
os.environ["UPLOAD_DIR"] = str(_TEST_DIR / "uploads")
os.environ["PRODUCT_PHOTO_DIR"] = str(_TEST_DIR / "product_photos")
os.environ["LOG_DIR"] = str(_TEST_DIR / "logs")
os.environ["SECRET_KEY"] = "test-secret"
os.environ.setdefault("OLLAMA_URL", "http://127.0.0.1:11434")

from database import seed as seed_module  # noqa: E402
from app import create_app  # noqa: E402
from app.models.db import query_one  # noqa: E402
from app.services.credentials import get_current_plaintext_for_admin  # noqa: E402
from app.services.rotation import SERVICE_NAME, SUPPORT_IMAGE_SERVICE_NAME  # noqa: E402


@pytest.fixture(scope="session", autouse=True)
def _seeded_database():
    seed_module.main()
    yield


@pytest.fixture()
def service_token(client):
    """The support-image-service token currently valid in THIS process --
    depends on `client` (which depends on `app`, which regenerates this
    credential on create_app() -- see app/services/rotation.py) so it's
    always read back after that happens, never a fixed constant.
    """
    token = get_current_plaintext_for_admin(SUPPORT_IMAGE_SERVICE_NAME)
    assert token, "expected a support-image-service token to have been generated on app startup"
    return token


@pytest.fixture()
def catalog_sync_token():
    """The catalog-sync-service token currently valid, exactly like a
    test/instructor tool would fetch it from an admin API -- never a fixed
    constant, since the real thing rotates (app/services/rotation.py).
    """
    token = get_current_plaintext_for_admin(SERVICE_NAME)
    assert token, "expected a catalog-sync-service token to have been generated by seeding"
    return token


@pytest.fixture()
def app():
    application = create_app()
    application.config.update(TESTING=True)
    return application


@pytest.fixture()
def client(app):
    return app.test_client()


@pytest.fixture()
def alice(client):
    """Log in as the seeded customer alice.customer; returns her user row."""
    client.post("/login", data={"username": "alice.customer", "password": "Customer123!"})
    return query_one("SELECT * FROM users WHERE username = 'alice.customer'")


@pytest.fixture()
def bob(client):
    client.post("/login", data={"username": "bob.customer", "password": "Customer123!"})
    return query_one("SELECT * FROM users WHERE username = 'bob.customer'")


@pytest.fixture()
def admin(client):
    client.post("/login", data={"username": "admin", "password": "AdminLab123!"})
    return query_one("SELECT * FROM users WHERE username = 'admin'")
